/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as counterSol from './Counter.sol/index.js';
export * as govTokenSol from './GovToken.sol/index.js';
export * as merit from './merit/index.js';