/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AuditLogInterface extends Interface {
    getFunction(nameOrSignature: "latest" | "owner" | "record" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Record"): EventFragment;

    encodeFunctionData(functionFragment: 'latest', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'record', values: [BytesLike, BytesLike, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'latest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'record', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace RecordEvent {
      export type InputTuple = [docId: BytesLike, version: BigNumberish, contentHash: BytesLike, uri: string, action: BigNumberish, actor: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [docId: string, version: bigint, contentHash: string, uri: string, action: bigint, actor: string, timestamp: bigint];
      export interface OutputObject {docId: string, version: bigint, contentHash: string, uri: string, action: bigint, actor: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AuditLog extends BaseContract {
    
    connect(runner?: ContractRunner | null): AuditLog;
    waitForDeployment(): Promise<this>;

    interface: AuditLogInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    latest: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, boolean] & {contentHash: string, version: bigint, exists: boolean }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    record: TypedContractMethod<
      [docId: BytesLike, contentHash: BytesLike, uri: string, action: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'latest'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, boolean] & {contentHash: string, version: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'record'): TypedContractMethod<
      [docId: BytesLike, contentHash: BytesLike, uri: string, action: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Record'): TypedContractEvent<RecordEvent.InputTuple, RecordEvent.OutputTuple, RecordEvent.OutputObject>;

    filters: {
      
      'Record(bytes32,uint64,bytes32,string,uint8,address,uint256)': TypedContractEvent<RecordEvent.InputTuple, RecordEvent.OutputTuple, RecordEvent.OutputObject>;
      Record: TypedContractEvent<RecordEvent.InputTuple, RecordEvent.OutputTuple, RecordEvent.OutputObject>;
    
    };
  }