/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace MeritOracle {
      
    export type HyperparametersStruct = {quota0Bps: BigNumberish, quota1Bps: BigNumberish, quota2Bps: BigNumberish, quota3Bps: BigNumberish, eduShareBps: BigNumberish, floor1Bps: BigNumberish, floor2Bps: BigNumberish, floor3Bps: BigNumberish, decay1Bps: BigNumberish, decay2Bps: BigNumberish, decay3Bps: BigNumberish, decayPeriod: BigNumberish}

    export type HyperparametersStructOutput = [quota0Bps: bigint, quota1Bps: bigint, quota2Bps: bigint, quota3Bps: bigint, eduShareBps: bigint, floor1Bps: bigint, floor2Bps: bigint, floor3Bps: bigint, decay1Bps: bigint, decay2Bps: bigint, decay3Bps: bigint, decayPeriod: bigint] & {quota0Bps: bigint, quota1Bps: bigint, quota2Bps: bigint, quota3Bps: bigint, eduShareBps: bigint, floor1Bps: bigint, floor2Bps: bigint, floor3Bps: bigint, decay1Bps: bigint, decay2Bps: bigint, decay3Bps: bigint, decayPeriod: bigint }
  
    }

  export interface MeritOracleInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "HYPERPARAM_ROLE" | "WEIGHT_SETTER_ROLE" | "contextHash" | "contextHashTopic" | "currentDay" | "dayForTimestamp" | "getRoleAdmin" | "grantRole" | "hasRole" | "hyperparameters" | "pushDailyTopicWeights" | "pushDailyWeights" | "renounceRole" | "revokeRole" | "setHyperparameters" | "supportsInterface" | "weightAt" | "weightAtTopic" | "weightOf" | "weightOfTopic"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DailyTopicWeightsUpdated" | "HyperparametersUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'HYPERPARAM_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'WEIGHT_SETTER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'contextHash', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contextHashTopic', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'currentDay', values?: undefined): string;
encodeFunctionData(functionFragment: 'dayForTimestamp', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hyperparameters', values?: undefined): string;
encodeFunctionData(functionFragment: 'pushDailyTopicWeights', values: [BigNumberish, BigNumberish, AddressLike[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'pushDailyWeights', values: [BigNumberish, AddressLike[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setHyperparameters', values: [MeritOracle.HyperparametersStruct]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'weightAt', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'weightAtTopic', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'weightOf', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'weightOfTopic', values: [AddressLike, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'HYPERPARAM_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WEIGHT_SETTER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contextHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contextHashTopic', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentDay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dayForTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hyperparameters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pushDailyTopicWeights', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pushDailyWeights', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setHyperparameters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weightAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weightAtTopic', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weightOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weightOfTopic', data: BytesLike): Result;
  }

  
    export namespace DailyTopicWeightsUpdatedEvent {
      export type InputTuple = [day: BigNumberish, topicId: BigNumberish, contextHash: BytesLike, count: BigNumberish];
      export type OutputTuple = [day: bigint, topicId: bigint, contextHash: string, count: bigint];
      export interface OutputObject {day: bigint, topicId: bigint, contextHash: string, count: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HyperparametersUpdatedEvent {
      export type InputTuple = [params: MeritOracle.HyperparametersStruct];
      export type OutputTuple = [params: MeritOracle.HyperparametersStructOutput];
      export interface OutputObject {params: MeritOracle.HyperparametersStructOutput };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MeritOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): MeritOracle;
    waitForDeployment(): Promise<this>;

    interface: MeritOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    HYPERPARAM_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    WEIGHT_SETTER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    contextHash: TypedContractMethod<
      [day: BigNumberish, ],
      [string],
      'view'
    >
    

    
    contextHashTopic: TypedContractMethod<
      [day: BigNumberish, topicId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    currentDay: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    dayForTimestamp: TypedContractMethod<
      [timestamp: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hyperparameters: TypedContractMethod<
      [],
      [MeritOracle.HyperparametersStructOutput],
      'view'
    >
    

    
    pushDailyTopicWeights: TypedContractMethod<
      [day: BigNumberish, topicId: BigNumberish, voters: AddressLike[], weights: BigNumberish[], newContextHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    pushDailyWeights: TypedContractMethod<
      [day: BigNumberish, voters: AddressLike[], weights: BigNumberish[], newContextHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setHyperparameters: TypedContractMethod<
      [params: MeritOracle.HyperparametersStruct, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    weightAt: TypedContractMethod<
      [voter: AddressLike, timepoint: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    weightAtTopic: TypedContractMethod<
      [voter: AddressLike, timepoint: BigNumberish, topicId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    weightOf: TypedContractMethod<
      [voter: AddressLike, day: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    weightOfTopic: TypedContractMethod<
      [voter: AddressLike, day: BigNumberish, topicId: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'HYPERPARAM_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'WEIGHT_SETTER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'contextHash'): TypedContractMethod<
      [day: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'contextHashTopic'): TypedContractMethod<
      [day: BigNumberish, topicId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'currentDay'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'dayForTimestamp'): TypedContractMethod<
      [timestamp: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hyperparameters'): TypedContractMethod<
      [],
      [MeritOracle.HyperparametersStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'pushDailyTopicWeights'): TypedContractMethod<
      [day: BigNumberish, topicId: BigNumberish, voters: AddressLike[], weights: BigNumberish[], newContextHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pushDailyWeights'): TypedContractMethod<
      [day: BigNumberish, voters: AddressLike[], weights: BigNumberish[], newContextHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setHyperparameters'): TypedContractMethod<
      [params: MeritOracle.HyperparametersStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'weightAt'): TypedContractMethod<
      [voter: AddressLike, timepoint: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'weightAtTopic'): TypedContractMethod<
      [voter: AddressLike, timepoint: BigNumberish, topicId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'weightOf'): TypedContractMethod<
      [voter: AddressLike, day: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'weightOfTopic'): TypedContractMethod<
      [voter: AddressLike, day: BigNumberish, topicId: BigNumberish, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'DailyTopicWeightsUpdated'): TypedContractEvent<DailyTopicWeightsUpdatedEvent.InputTuple, DailyTopicWeightsUpdatedEvent.OutputTuple, DailyTopicWeightsUpdatedEvent.OutputObject>;
getEvent(key: 'HyperparametersUpdated'): TypedContractEvent<HyperparametersUpdatedEvent.InputTuple, HyperparametersUpdatedEvent.OutputTuple, HyperparametersUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'DailyTopicWeightsUpdated(uint48,uint32,bytes32,uint256)': TypedContractEvent<DailyTopicWeightsUpdatedEvent.InputTuple, DailyTopicWeightsUpdatedEvent.OutputTuple, DailyTopicWeightsUpdatedEvent.OutputObject>;
      DailyTopicWeightsUpdated: TypedContractEvent<DailyTopicWeightsUpdatedEvent.InputTuple, DailyTopicWeightsUpdatedEvent.OutputTuple, DailyTopicWeightsUpdatedEvent.OutputObject>;
    

      'HyperparametersUpdated(tuple)': TypedContractEvent<HyperparametersUpdatedEvent.InputTuple, HyperparametersUpdatedEvent.OutputTuple, HyperparametersUpdatedEvent.OutputObject>;
      HyperparametersUpdated: TypedContractEvent<HyperparametersUpdatedEvent.InputTuple, HyperparametersUpdatedEvent.OutputTuple, HyperparametersUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }