/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernorCountingFractionalRebalance__factory } from './GovernorCountingFractionalRebalance__factory.js';