/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorCountingFractionalRebalanceSol from './GovernorCountingFractionalRebalance.sol/index.js';
export type { governorCountingFractionalRebalanceSol };
import type * as meritGovernorSol from './MeritGovernor.sol/index.js';
export type { meritGovernorSol };
import type * as meritOracleSol from './MeritOracle.sol/index.js';
export type { meritOracleSol };